Controllers/PanelController.cs
using System.Threading.Tasks;
using dotnet_blog_mvc.Data.FileManager;
using dotnet_blog_mvc.Data.Repository;
using dotnet_blog_mvc.Models;
using dotnet_blog_mvc.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
namespace dotnet_blog_mvc.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PanelController : Controller
    {
        private readonly IRepository _repo;
        private readonly IFileManager _fileManager;
        public PanelController(IRepository repo, IFileManager fileManager)
        {
            _repo = repo;
            _fileManager = fileManager;
        }

        public IActionResult Index()
        {
            var posts = _repo.GetAllPosts();
            return View(posts);
        }


        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id is null)
            {
                return View(new PostViewModel());
            }
            else
            {
                var postToEdit = _repo.GetPostById((int)id);
                return View(new PostViewModel
                {
                    Id = postToEdit.Id,
                    Title = postToEdit.Title,
                    Body = postToEdit.Body,
                    CurrentImage = postToEdit.Image,
                    Description = postToEdit.Description,
                    Tags = postToEdit.Tags,
                    Category = postToEdit.Category
                });
            }

        }

        [HttpPost]
        public async Task<IActionResult> Edit(PostViewModel vm)
        {
            var post = new Post
            {
                Id = vm.Id,
                Title = vm.Title,
                Body = vm.Body,
                Description = vm.Description,
                Tags = vm.Tags,
                Category = vm.Category,
            };

            if (vm.Image is null)
            {
                post.Image = vm.CurrentImage;
            }
            else
            {
                post.Image = await _fileManager.SaveImageAsync(vm.Image);
            }

            if (post.Id > 0)
            {
                _repo.UpdatePost(post);
            }
            else
            {
                // if it is a new post, it will have an Id=0
                _repo.AddPost(post);
            }

            if (await _repo.SaveChangesAsync())
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(vm);
            }

        }

        [HttpGet]
        public async Task<IActionResult> Remove(int id)
        {
            _repo.RemovePost(id);
            if (await _repo.SaveChangesAsync())
            {
                return RedirectToAction("Index");
            }
            else
            {
                return NotFound();
            }

        }

    }
}

Views/Panel/Edit.cshtml
@model PostViewModel

@{

}
<link rel="stylesheet" href="~/lib/Trumbowyg-main/dist/ui/trumbowyg.min.css">
<div>
    <form asp-controller="Panel" asp-action="Edit" method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <div>
            <label>Title</label>
            <input asp-for="Title" />
        </div>
        <div>
            <label>Description</label>
            <input asp-for="Description" />
        </div>
        <div>
            <label>Tags</label>
            <input asp-for="Tags" />
        </div>
        <div>
            <label>Category</label>
            <select asp-for="Category">
                <option value="Travel">Travel</option>
                <option value="Programming">Programming</option>
                <option value="Photography">Photography</option>
            </select>
        </div>
        <div>
            <label>Body</label>
            <textarea id="editor" asp-for="Body"></textarea>
        </div>
        <div>
            <label>Image</label>
            <input asp-for="CurrentImage" type="hidden">
            <input asp-for="Image" />
        </div>
        <button type="submit">Submit</button>
    </form>
</div>

@section scripts {
<script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery-3.3.1.min.js"><\/script>')</script>
<script src="~/lib/Trumbowyg-main/dist/trumbowyg.min.js"></script>
<script>
    $('#editor').trumbowyg();
</script>
}

Views/Panel/Index.cshtml
@model IEnumerable<Post>

@{

}
<h2>Admin Page</h2>

<a asp-controller="Panel" asp-action="Edit">Create</a>


<div>
    <ul>
        @foreach (var post in Model)
        {
            <li>
                <a asp-controller="Home" asp-action="Post" asp-route-id="@post.Id">@post.Title</a>
                <a asp-controller="Panel" asp-action="Edit" asp-route-id="@post.Id">Edit</a>
                <a asp-controller="Panel" asp-action="Remove" asp-route-id="@post.Id">Remove</a>
            </li>

        }
    </ul>
</div>